ProjectMutia/urls.py
from django.contrib import admin
from django.urls import path, include
import mutiaishere.urls

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include(mutiaishere.urls)),
]

mutiaishere/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mutiaishere'
urlpatterns = [
	path('', views.home, name='home'),
	path('home', views.home, name='home'),
	path('experience', views.experience, name='experience'),
	path('registration', views.registration, name='registration'),
	path('contactMe', views.contactMe, name='contactMe'),
]

mutiaishere/models.py
from django.db import models

# Create your models here.

mutiaishere/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
	return render(request, 'home.html')
	
def experience(request):
	return render(request, 'Experience.html')
	
def registration(request):
	return render(request, 'pendaftaran.html')
	
def contactMe(request):
	return render(request, 'ContactMe.html')

mutiaishere/templates/ContactMe.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="description" content="Story 3">
	<meta name="author" content="Mutia Rahmatun Husna">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/web.css' %}">
    

	<title>
		Find Me Here!!
	</title>

</head>

<body>
	<ul>
	  <li><a href="{% url 'mutiaishere:home' %}">Home</a></li>
	  <li><a href="{% url 'mutiaishere:experience' %}">Experience</a></li>
	  <li><a href="{% url 'mutiaishere:contactMe' %}">Contact Me</a></li>
	  <la><a href="{% url 'mutiaishere:registration' %}">Registation</a></la>
	</ul>



</body>
</html>

mutiaishere/templates/Experience.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="description" content="Story 3">
	<meta name="author" content="Mutia Rahmatun Husna">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/web.css' %}">
    

	<title>
		Find Me Here!!
	</title>

</head>

<body>
	<ul>
	  <li><a href="{% url 'mutiaishere:home' %}">Home</a></li>
	  <li><a href="{% url 'mutiaishere:experience' %}">Experience</a></li>
	  <li><a href="{% url 'mutiaishere:contactMe' %}">Contact Me</a></li>
	  <la><a href="{% url 'mutiaishere:registration' %}">Registation</a></la>
	</ul>



</body>
</html>

mutiaishere/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="description" content="Story 3">
	<meta name="author" content="Mutia Rahmatun Husna">

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/web.css' %}">
	
    

	<title>
		Find Me Here!!
	</title>

</head>

<body>
	<ul>
	  <li><a href="{% url 'mutiaishere:home' %}">Home</a></li>
	  <li><a href="{% url 'mutiaishere:experience' %}">Experience</a></li>
	  <li><a href="{% url 'mutiaishere:contactMe' %}">Contact Me</a></li>
	  <la><a href="{% url 'mutiaishere:registration' %}">Registation</a></la>
	</ul>

	<h1>It's Me!!</h1>

	<img src="{% static 'media/mutia.JPG' %}" alt="Trulli" class="center" width="300" height="300">


<p>Aku adalah seorang pemimpi yang sedang meraih mimpi-mimpiku</p>



</body>

<body>
	
<p>Nama : Mutia Rahmatun Husna </p>
<p>Birth Place : Medan </p>
<p>Date of Birth : 19 July 2000</p>
<p>Hobby : Reading a book</p>

</body>
</html>

mutiaishere/templates/pendaftaran.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="description" content="Story 3">
  <meta name="author" content="Mutia Rahmatun Husna">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/web.css' %}">
  
  
  <title>
    Find Me Here!!
  </title>

</head>

<body>
  <ul>
	<li><a href="{% url 'mutiaishere:home' %}">Home</a></li>
    <li><a href="{% url 'mutiaishere:experience' %}">Experience</a></li>
	<li><a href="{% url 'mutiaishere:contactMe' %}">Contact Me</a></li>
	<la><a href="{% url 'mutiaishere:registration' %}">Registation</a></la>
  </ul>

<form>
  <div class="form-group">
    <label for="inputName">Nama</label>
    <input type="nameHelp" class="form-control" id="inputName" aria-describedby="nameHelp" placeholder="Enter name">
  </div>
  <div class="form-group">
    <label for="inputDate">Tanggal Lahir</label>
    <input type="date" class="form-control" id="inputDate" aria-describedby="dateHelp" placeholder="Enter birthday">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="inputUserName">Username</label>
    <input type="usernameHelp" class="form-control" id="inputUserName" aria-describedby="usernameHelp" placeholder="Enter username">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword2">Password</label>
    <input type="password2" class="form-control" id="exampleInputPassword2" placeholder="Password">
    <small id="passwordHelp" class="form-text text-muted">Please type again your password.</small>
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</body>
</html>